test

diff --git a/.github/workflows/build-mudlet-win.yml b/.github/workflows/build-mudlet-win.yml
--- a/.github/workflows/build-mudlet-win.yml
+++ b/.github/workflows/build-mudlet-win.yml
@@ -66,11 +66,28 @@ jobs:
 
     - name: (Windows) Run QTest
       shell: msys2 {0}
+      # run: |
+      #   export QT_FATAL_WARNINGS=1
+      #   export QTEST_FUNCTION_TIMEOUT=30000
+      #   export QT_LOGGING_RULES="*.debug=true;*.warning=true;qt.qpa.*=true"
+      #   ctest --test-dir $GITHUB_WORKSPACE/build-$MSYSTEM/test --output-on-failure -V 2>&1
       run: |
         export QT_FATAL_WARNINGS=1
         export QTEST_FUNCTION_TIMEOUT=30000
         export QT_LOGGING_RULES="*.debug=true;*.warning=true;qt.qpa.*=true"
-        ctest --test-dir $GITHUB_WORKSPACE/build-$MSYSTEM/test --output-on-failure -V 2>&1
+
+        set +e  # continuer même si ctest échoue
+        ctest --test-dir $GITHUB_WORKSPACE/build-$MSYSTEM/test --output-on-failure -V
+        TEST_EXIT_CODE=$?
+        set -e
+
+        if [ $TEST_EXIT_CODE -ne 0 ]; then
+          echo "❌ Some tests failed! Showing LastTest.log and LastTestsFailed.log"
+          cat $GITHUB_WORKSPACE/build-$MSYSTEM/test/Testing/Temporary/LastTest.log
+          echo "---- Failed tests ----"
+          cat $GITHUB_WORKSPACE/build-$MSYSTEM/test/Testing/Temporary/LastTestsFailed.log
+          exit $TEST_EXIT_CODE
+        fi
 
     - name: (Windows) Run Lua tests
       timeout-minutes: 5
